
project_id = "aaiyxtbovepseasghtth"
[api]
port = 54321
schemes = ["http", "https"]
host = "127.0.0.1"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[edge_functions]]
path = "generate-seasonal-outfits"
verify_jwt = false
